### ISSUE TITLE
PHP Fatal error:  Uncaught PDOException: SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax;

### ISSUE THREAD

**Issue by Aquive** [DBDiff/DBDiff#120]
Hi, I get below error on --type=data or all. --type=schema works as expected. How can I solve it?

pp@6bb82a2c0270:~/DBDiff$ ./dbdiff server1.small:server2.stage-small --type=data
ℹ Now calculating data diff for table `admin_rule`
✖ Unexpected error: SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '-small.admin_rule as a
            LEFT JOIN kp-stage-small.admin_rule as b ON `' at line 1 (SQL: SELECT CONVERT(`a`.`rule_id` USING utf8) as `rule_id`,CONVERT(`a`.`role_id` USING utf8) as `role_id`,CONVERT(`a`.`resource_id` USING utf8) as `resource_id`,CONVERT(`a`.`privileges` USING utf8) as `privileges`,CONVERT(`a`.`assert_id` USING utf8) as `assert_id`,CONVERT(`a`.`role_type` USING utf8) as `role_type`,CONVERT(`a`.`permission` USING utf8) as `permission` FROM kp-small.admin_rule as a
            LEFT JOIN kp-stage-small.admin_rule as b ON `a`.`rule_id` = `b`.`rule_id` WHERE `b`.`rule_id` IS NULL
        )
PHP Fatal error:  Uncaught PDOException: SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '-small.admin_rule as a
            LEFT JOIN kp-stage-small.admin_rule as b ON `' at line 1 in /data/web/DBDiff/vendor/illuminate/database/Illuminate/Database/Connection.php:299
Stack trace:
#0 /data/web/DBDiff/vendor/illuminate/database/Illuminate/Database/Connection.php(299): PDO->prepare('SELECT CONVERT(...')
#1 /data/web/DBDiff/vendor/illuminate/database/Illuminate/Database/Connection.php(617): Illuminate\Database\Connection->Illuminate\Database\{closure}(Object(Illuminate\Database\MySqlConnection), 'SELECT CONVERT(...', Array)
#2 /data/web/DBDiff/vendor/illuminate/database/Illuminate/Database/Connection.php(581): Illuminate\Database\Connection->runQueryCallback('SELECT CONVERT(...', Array, Object(Closure))
#3 /data/web/DBDiff/vendor/illuminate/database/Illuminate/Database/Connection.php(304): I in /data/web/DBDiff/vendor/illuminate/database/Illuminate/Database/Connection.php on line 625

**Comment by rzroth** [comment]
There is a flaw in DBDiff that doesn't account for tables with '-' in the name, because it tries to make a illegally named JOIN 
Still working on my cases, I suspect you will need to rename the database 
In my case, it is only tables with '-' in the name
I'm looking into the code to see how that might addresssed
