### ISSUE TITLE
A Symfony error about indentation with tabs

### ISSUE THREAD

**Issue by rolka** [DBDiff/DBDiff#52]
Hi, I ran this: php dbdiff server1.db1:server1.db2 and got an error about indentation with tabs

```
> php dbdiff server1.db1:server1.db2
✖ Unexpected error: A YAML file cannot contain tabs as indentation at line 27 (near "           ").

Fatal error: Uncaught Symfony\Component\Yaml\Exception\ParseException: A YAML file cannot contain tabs as indentation at line 27 (near "                "). in C:\dbdiff\DBDiff\vendor\symfony\yaml\Parser.php:125
Stack trace:
#0 C:\dbdiff\DBDiff\vendor\symfony\yaml\Parser.php(80): Symfony\Component\Yaml\Parser->doParse('output.sql', false, false, false)
#1 C:\dbdiff\DBDiff\vendor\symfony\yaml\Yaml.php(65): Symfony\Component\Yaml\Parser->parse('server1:\r\n user...', false, false, false)
#2 C:\dbdiff\DBDiff\src\Params\FSGetter.php(19): Symfony\Component\Yaml\Yaml::parse('server1:\r\n user...')
#3 C:\dbdiff\DBDiff\src\Params\ParamsFactory.php(20): DBDiff\Params\FSGetter->getParams()
#4 C:\dbdiff\DBDiff\src\DBDiff.php(18): DBDiff\Params\ParamsFactory::get()
#5 C:\dbdiff\DBDiff\dbdiff(8): DBDiff\DBDiff->run()
#6 {main}
  thrown in C:\dbdiff\DBDiff\vendor\symfony\yaml\Parser.php on line 125
```

How can I fix this?

**Comment by jhbsk** [comment]
Try removing any tabs you might have in your `.dbdiff` file. If you can't see tabs, use an editor which allows you to see hidden characters like spaces ([Atom](https://atom.io/) is a good editor with the `Toggle Invisibles` option)
