### ISSUE TITLE
Can't Connect to target database

### ISSUE THREAD

**Issue by neerajUdai** [DBDiff/DBDiff#89]
Using PHP 7.2

Set everything up according to the instructions but still getting the issue:-
"Can't Connect to target database"

Much simpler solution and worked like a charm.
https://code.google.com/archive/p/sql-dump-schema-diff/downloads

**Comment by matdodgson** [comment]
I'm also having the same problem (the target database). I'm also using Php 7.2 and I'm on Ubuntu 18.10. I assume the problem is to do with the mysql library for PHP. Maybe some more detailed error output would be helpful?

**Comment by amanullah92** [comment]
I added log in the relevant php file (src/DB/DBManager.php) where the error was thrown. It pointed to the error :

DOException: PDO::__construct(): The server requested authentication method unknown to the client [caching_sha2_password] in /Users/mohdamandullah/code_repo/opensource/DBDiff/vendor/illuminate/database/Illuminate/Database/Connectors/Connector.php:47
Stack trace:
#0 /Users/mohdamandullah/code_repo/opensource/DBDiff/vendor/illuminate/database/Illuminate/Database/Connectors/Connector.php(47): PDO->__construct('mysql:host=127....', 'root', '**xxx*', Array)
#1 /Users/mohdamandullah/code_repo/opensource/DBDiff/vendor/illuminate/database/Illuminate/Database/Connectors/MySqlConnector.php(20): Illuminate\Database\Connectors\Connector->createConnection('mysql:host=127....', Array, Array)
#2 /Users/mohdamandullah/code_repo/opensource/DBDiff/vendor/illuminate/database/Illuminate/Database/Connectors/ConnectionFactory.php(57): Illuminate\Database\Connectors\MySqlConnector->connect(Array)
#3 /Users/mohdamandullah/code_repo/opensource/DBDiff/vendor/illuminate/database/Illuminate/Database/Connectors/ConnectionFactory.php(46): Illuminate\Database\Connectors\ConnectionFactory->createSingleConnection(Array)
#4 /Users/mohdamandullah/code_repo/opensource/DBDiff/vendor/illuminate/database/Illuminate/Database/DatabaseManager.php(176): Illuminate\Database\Connectors\ConnectionFactory->make(Array, 'source')
#5 /Users/mohdamandullah/code_repo/opensource/DBDiff/vendor/illuminate/database/Illuminate/Database/DatabaseManager.php(64): Illuminate\Database\DatabaseManager->makeConnection('source')
#6 /Users/mohdamandullah/code_repo/opensource/DBDiff/vendor/illuminate/database/Illuminate/Database/Capsule/Manager.php(107): Illuminate\Database\DatabaseManager->connection('source')
#7 /Users/mohdamandullah/code_repo/opensource/DBDiff/src/DB/DBManager.php(38): Illuminate\Database\Capsule\Manager->getConnection('source')
#8 /Users/mohdamandullah/code_repo/opensource/DBDiff/src/DB/DBManager.php(32): DBDiff\DB\DBManager->testResource(Array, 'source')
#9 /Users/mohdamandullah/code_repo/opensource/DBDiff/src/DB/DiffCalculator.php(19): DBDiff\DB\DBManager->testResources(Object(stdClass))
#10 /Users/mohdamandullah/code_repo/opensource/DBDiff/src/DBDiff.php(23): DBDiff\DB\DiffCalculator->getDiff(Object(stdClass))
#11 /Users/mohdamandullah/code_repo/opensource/DBDiff/dbdiff(8): DBDiff\DBDiff->run()
